### ISSUE TITLE
administrator kann keine Shell aufmachen

### ISSUE THREAD

**Issue by linuxmuster** [linuxmuster/linuxmuster-client-auth#2]
wenn man sich nach der paketinstallation als pgmadmin anmeldet, kann man kein gnome-terminal öffnen?

**Comment by anschuetz** [comment]
der pgmadmin ist als Programm-Admin unter Windows gedacht. Er hat im Linuxclient keine Funktion. Ob eine Shell geöffnet werden darf, legt man in der Sophomorix-Config fest. Die dort eingestellten Werte gelten für neue Benutzer. 
Bei alten Benutzern muss man eine login-shell mit usermod einstellen.
