### ISSUE TITLE
Beim ersten Reboot nach der Installation funktioniert die Grafik nicht

### ISSUE THREAD

**Issue by linuxmuster** [linuxmuster/linuxmuster-client-auth#4]
Nach der Installation des linuxmuster-client-auth kommt beim Hochfahren eine Fehlermeldung bezüglich der Grafik. Es kann nur in einem einfachen grafischen Mode gestartet werden. 

Ein weiterer Reboot klappt anschließend ohne Probleme.

Reproduzierbar in virtualbox und realen Testumgebungen :(

**Comment by foer** [comment]
IsIst mit aktuellen Ubuntus >= 14.04 nicht reproduzierbar
