### ISSUE TITLE
Auth-Paket lässt sich unter Kubuntu 12.04 nicht installieren

### ISSUE THREAD

**Issue by Ray-Ven** [linuxmuster/linuxmuster-client-auth#5]
Momentan kann ich das Paket unter kubuntu nicht installieren:

    dpkg: Fehler beim Bearbeiten von linuxmuster-client-auth (--configure):
    Unterprozess installiertes post-installation-Skript gab den Fehlerwert 123
    zurück>
    Es wurde kein Apport-Bericht verfasst, da das Limit MaxReports bereits
    erreicht ist Fehler traten auf beim Bearbeiten von:
    linuxmuster-client-auth
    E: Sub-process /usr/bin/dpkg returned an error code (1)

Habe noch einiges unsinniges probiert. Erfolglos.d
Sitze jetzt am postinst Skript, welches m.E. folgendes macht:
debconf starten
administrator und pgmadmin in die sudoerslist
per debconf ein paar Sachen abfragen
konfiguration patchen
ldap fixen
und abbrechen tut das Skript doch nur, wenn das Skript ohne Argument
aufgerufen wird oder debconf nicht da ist.
Beides kann aber nicht sein?!

Woran könnte es denn liegen?! Ich hab hier echt schon einiges versucht - es
will einfach nicht.

Wäre für jede Hilfe dankbar!

**Comment by foer** [comment]
Das Paket ist nicht für Kubuntu < 14.04 geeignet, da nicht an den Displaymanager kdm angepasst!

**Comment by Ray-Ven** [comment]
Das geht wunderbar wenn man, wie ohnehin vorgesehen, lightdm statt kdm 
verwendet
schau mal hier:
https://www.linuxmuster.net/wiki/anwenderwiki:linuxclient:kubuntu


-- 
Medien & IT-Administration der Irena-Sendler-Schule
Am Pfeilshof 20
22393 Hamburg

**Comment by foer** [comment]
Ja klar...dann gehts!

Gruß
